<?php

$lottryItems = [

			[
				'id'=>1,
				'lottry_id'=>12,
				'name'=>'9600cp大礼包',
				'sub_name'=>'一等奖',
				'amount'=>1,
				'total'=>1,
				'probability'=>0.1,
				'remark'=>'尊享体检女士套餐/尊享体检男士套餐',
				'min_angles'=>10,
				'max_angles'=>40
			],
			[
				'id'=>2,
				'lottry_id'=>12,
				'name'=>'5180cp大礼包',
				'sub_name'=>'二等奖',
				'amount'=>1,
				'total'=>1,
				'probability'=>0.9,
				'remark'=>'巴厘岛纯玩大礼包',
				'min_angles'=>70,
				'max_angles'=>90
			],
			[
				'id'=>3,
				'lottry_id'=>12,
				'name'=>'536cp大礼包',
				'sub_name'=>'三等奖',
				'amount'=>1,
				'total'=>1,
				'probability'=>4,
				'remark'=>'咖啡礼盒套装',
				'min_angles'=>110,
				'max_angles'=>140
			],
			[
				'id'=>4,
				'lottry_id'=>12,
				'name'=>'300cp优惠券',
				'sub_name'=>'四等奖',
				'amount'=>1,
				'total'=>1,
				'probability'=>15,
				'remark'=>'300cp优惠券',
				'min_angles'=>170,
				'max_angles'=>190
			],
			[
				'id'=>5,
				'lottry_id'=>12,
				'name'=>'200cp优惠券',
				'sub_name'=>'五等奖',
				'amount'=>1,
				'total'=>1,
				'probability'=>20,
				'remark'=>'200cp优惠券',
				'min_angles'=>210,
				'max_angles'=>240
			],
			[
				'id'=>6,
				'lottry_id'=>12,
				'name'=>'100cp优惠券',
				'sub_name'=>'六等奖',
				'amount'=>1,
				'total'=>1,
				'probability'=>20,
				'remark'=>'100cp优惠券',
				'min_angles'=>270,
				'max_angles'=>290
			],
			[
				'id'=>6,
				'lottry_id'=>12,
				'name'=>'100cp优惠券',
				'sub_name'=>'七等奖',
				'amount'=>1,
				'total'=>1,
				'probability'=>40,
				'remark'=>'100cp优惠券',
				'min_angles'=>310,
				'max_angles'=>350
			]
	];